### PR TITLE
Setup environment properly

### PR DESCRIPTION
**Pull request by StEvUgnIn**

### CODE REVIEW

**Comment by StEvUgnIn** [comment]
@iainnash Please review this PR and authorize the deployment on Vercel

**Comment by iainnash** [comment]
I understand some of the changes but can you provide the context for the changes especially with the change to how the environment is retrieved within the application?

**Comment by StEvUgnIn** [comment]
> I understand some of the changes but can you provide the context for the changes especially with the change to how the environment is retrieved within the application?

Hi @iainnash, using `process.env` directly allows to retrieve direct values from the environment instead of creating a dependency for a TypeScript file:
```ts
// formerly
import BAR from '../../utils/env-var.ts'
...
foo(BAR)
...
// proposed
// BAR is already in process env
...
foo(process.env.NEXT_PUBLIC_BAR)
...
// alternatively
const { BAR: NEXT_PUBLIC_BAR } = process.env
...
foo(BAR)
...
```

TypeScript has type inference, so it won't make a problem and I believe that you consider every variable passed to environment as type string which is standard on Node.js.

Based on the following assumption:
```ts
export function foo(bar: string) {
...
}
```

If the argument is typed, the argument passed will infer its type to fit paramater. If it cannot infer, it will raise an TS exception.

**Comment by iainnash** [comment]
The idea here for the dependency on the external file for environment variables is that the exports are known for that so it's easier to track down where particular environment variables are being used.

**Pull request closed without merging**
